### PR TITLE
Add message

### PR DESCRIPTION
**Pull request by sbglasius**
Added [message: ] as an option for the service, as Grails now supports this in it's message implementation for Controller/Taglib artefacts. Now includes a unit spec to make some basic tests.

Did a cleanup of the plugin, bumped it to version 1.0-SNAPSHOT and encourages the plugin author to release it as 1.0

### CODE REVIEW

**Comment by sbglasius** [comment]
Apparently I accidently deleted the pull-request before it was merged. 

Please include this in the plugin.

**Comment by sbglasius** [comment]
Is this plugin still maintained by adaptivecomputing or would you like me to take over?

**Comment by bluesliverx** [comment]
Thanks for the help!  Sorry my notifications have been off apparently...

**Comment by sbglasius** [comment]
That happens - glad you saw it.

Med venlig hilsen / Best regards,
Søren Berg Glasius

Hedevej 1, Gl. Rye, DK-8680 Ry, Denmark
Mobile: (+45)40449188, Skype: sbglasius
--- Press ESC once to quit - twice to save the changes.

2014-03-24 15:55 GMT+01:00 Brian Saville notifications@github.com:

**Comment by bluesliverx** [comment]
Working on releasing 1.0 now

**Comment by bluesliverx** [comment]
Released.

**Pull request merged**
